name = "Yoda"
uuid = "db43a6b5-d1be-4ac2-9828-026fb2246ab5"
authors = ["Salvatore La Cagnina"]
version = "1.0.0-DEV"

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.6"
StatsBase = "0.32, 0.33, 0.34"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
